---
- name: Install proxmoxer module
  ansible.builtin.pip:
    name: proxmoxer
  become: true

- name: Create CT for services that starts when proxmox reboots
  community.general.proxmox:
    node: '{{ node }}'
    api_user: '{{ promox_api_id }}'
    api_password: '{{ proxmox_default_root }}'
    api_host: '{{ api_host }}'
    password: '{{ proxmox_default_root }}'
    onboot: true
    hostname: '{{ hostname }}'
    disk: "{{ disk_storage }}:{{ container_disk_usage }}"
    cores: "{{ cores }}"
    cpus: "{{ cpus }}"
    memory: "{{ memory }}"
    storage: local
    state: "{{ state }}"
    netif: '{"net0":"name=eth0,ip=dhcp,ip6=dhcp,bridge=vmbr0"}'
    pubkey: "{{ default_ssh_key }}"
    ostemplate: "{{ ostemplate }}"

- name: Turn on container
  community.general.proxmox:
    node: '{{ node }}'
    api_user: '{{ promox_api_id }}'
    api_password: '{{ proxmox_default_root }}'
    api_host: '{{ api_host }}'
    password: '{{ proxmox_default_root }}'
    hostname: '{{ hostname }}'
    state: started
