galaxy_info:
  author: Ted Kent
  description: A role to create and configure a Proxmox container using the proxmoxer module.
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - buster
    - name: Ubuntu
      versions:
        - focal
  galaxy_tags:
    - proxmox
    - container

dependencies:
  - role: geerlingguy.pip
    vars:
      pip_install_packages:
        - proxmoxer
  - role: community.general
